export enum Environment {
    PORT = 'PORT',
    POSTGRES_URL = 'POSTGRES_URL',
    PASSWORD_SALT = 'PASSWORD_SALT',
    JWT_ACCESS_SECRET_KEY = 'JWT_ACCESS_SECRET_KEY',
    JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY',
    JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
    JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
}
